// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-hcuboJNDvlLaE5UmAubht0WGWg6sqRo',
    appId: '1:375686752503:web:9488e879424f1dc41d0bf2',
    messagingSenderId: '375686752503',
    projectId: 'heat-e9529',
    authDomain: 'heat-e9529.firebaseapp.com',
    storageBucket: 'heat-e9529.appspot.com',
    measurementId: 'G-CLEW4DGLF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7eJj_fHQWXGJi7V62QImzzHWgqRz8M0',
    appId: '1:375686752503:android:28658e466c6884bf1d0bf2',
    messagingSenderId: '375686752503',
    projectId: 'heat-e9529',
    storageBucket: 'heat-e9529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8dn7XfuPhNUadDk-WiU7tmBHuiaq0caY',
    appId: '1:375686752503:ios:0e9c0c97c23e55591d0bf2',
    messagingSenderId: '375686752503',
    projectId: 'heat-e9529',
    storageBucket: 'heat-e9529.appspot.com',
    androidClientId: '375686752503-0lrkib0sord75mk5kfgfo1irrt07p58a.apps.googleusercontent.com',
    iosClientId: '375686752503-gmg8go5dsg27c8menrengjols4pnkd3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.heat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8dn7XfuPhNUadDk-WiU7tmBHuiaq0caY',
    appId: '1:375686752503:ios:8cf7911497683ea71d0bf2',
    messagingSenderId: '375686752503',
    projectId: 'heat-e9529',
    storageBucket: 'heat-e9529.appspot.com',
    androidClientId: '375686752503-0lrkib0sord75mk5kfgfo1irrt07p58a.apps.googleusercontent.com',
    iosClientId: '375686752503-4irl22q2mdivaknumaj3hnjqdv0rvk6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.heat.RunnerTests',
  );
}
